# дообучение двухбашенной модели

берем предобученный bi энкодер и учим его на наших парах. лосс InfoNCE с in-batch негативами)) , то есть sampled softmax, где негативы для каждого запроса это позитивы остальных запросов в батче. веса башен общие, размораживаем все, кроме матрицы токенов

большой батч нужен для хороших негативов, а в память влезает мало. попробовал применить GradCache: считаем эмбеддинги всего батча без графа, потом пересчитываем маленькими кусками с градиентом

In [ ]:
import sys, time, random
sys.path.insert(0, "..")

from pathlib import Path
import numpy as np
import polars as pl
import torch
from datasets import Dataset
from sentence_transformers import SentenceTransformer, SentenceTransformerTrainer, SentenceTransformerTrainingArguments, losses
from sentence_transformers.training_args import BatchSamplers

from src.text import item_text, query_text
from src.metrics import recall_at_k, recall_by_slice
from src.search import encode, topk

PROC = Path("../data/processed")
MODELS_DIR = Path("../data/models")
MODELS_DIR.mkdir(exist_ok=True)

MODELS = {"user-bge-m3": dict(name="deepvk/USER-bge-m3", q="", p=""), "bge-m3": dict(name="BAAI/bge-m3", q="", p=""), "e5-base": dict(name="intfloat/multilingual-e5-base", q="query: ", p="passage: "), "e5-large-instruct": dict(name="intfloat/multilingual-e5-large-instruct", q="Instruct: Given a search query, retrieve service ads that match it\nQuery: ", p="")}
MODEL_KEY = "user-bge-m3"
RUN_NAME = MODEL_KEY + "-ft1"

QUERY_LEN = 32 # запросы короткие, 32 токенов хватает с запасом
ITEM_LEN = 160 # заголовок + вид/тип + услуги + кусок описания
BATCH = 256 # эффективный батч, столько негативов видит каждый запрос
MINI_BATCH = 16 # сколько реально влезает в память за один проход
LR = 2e-5
TARGET_HOURS = 2.5 # сколько готовы ждать одну эпоху. число пар подберем под это

random.seed(0)
torch.manual_seed(0)
cfg = MODELS[MODEL_KEY]

/Users/amirhamidullin/PycharmProjects/avito_recsys/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/var/folders/lz/_v3mf0j971z3l63wg5q45y8c0000gn/T/ipykernel_3994/4231437145.py:9: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer, SentenceTransformerTrainer, SentenceTransformerTrainingArguments, losses
/var/folders/lz/_v3mf0j971z3l63wg5q45y8c0000gn/T/ipykernel_3994/4231437145.py:10: DeprecationWarning: Importing from 'sentence_transformers.training_args' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.training_args' instead.
  from sentence_transformers.training_args import BatchSamplers

## Пары для обучения

Из трейна без валидационных запросов. текст запроса и объявления собираем теми же шаблонами, что при поиске иначе модель на обучении и на инференсе увидит разное

In [ ]:
train = pl.read_parquet(PROC / "train_rest.parquet", columns=["search_query", "search_infm_params_text", "item_id", "item_title_raw", "item_infm_params_text", "item_description_raw"])
print("строк в трейне", len(train))

# одну и ту же пару текстов учить дважды смысла нет
train = train.unique(subset=["search_query", "search_infm_params_text", "item_id"], maintain_order=True)   # порядок фиксируем иначе выборка пар не воспроизводится
print("уникальных пар", len(train))

t = time.time()
anchors = [cfg["q"] + query_text(q, p) for q, p in zip(train["search_query"], train["search_infm_params_text"])]
positives = [cfg["p"] + item_text(ti, pa, de) for ti, pa, de in zip(train["item_title_raw"], train["item_infm_params_text"], train["item_description_raw"])]
print("тексты собраны за", round((time.time() - t) / 60, 1), "минут")
print("запрос", anchors[0])
print("объявление", positives[0][:250])

строк в трейне: 494646
уникальных пар: 459581

тексты собраны за 0.5 минут

пример пары:
  запрос: щечки яблочки инъекция
  объявление: ботокс лица. вид услуги: красота, здоровье. тип услуги: косметология. услуги: инъекции ботокса в брови, инъекции ботокса вокруг глаз, инъекции ботокса в лоб. 🔈акция до 31 мая ⏳❤️‍🔥 ✨подари своей коже молодость и сияние✨ 🌝 устали от возрастных изменен

## Модель

Матрицу токенов замораживаем: в xlm-r это четверть миллиона строк по 1024, почти половина всех параметров, а учить ее на нашем объеме незачем

In [ ]:

model = SentenceTransformer(cfg["name"], device="mps", config_kwargs={"attention_probs_dropout_prob": 0.0})
model.max_seq_length = ITEM_LEN

emb = model[0].auto_model.embeddings.word_embeddings
emb.weight.requires_grad_(False)
total = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("параметров всего", round(total / 1e6), "млн, обучаемых", round(trainable / 1e6), "млн")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 8350.76it/s]

параметров всего: 359 млн, обучаемых: 312 млн

## подсчет времени

короткий прогон на нескольких шагах чтобы понять скорость и выбрать, сколько пар взять в эпоху

In [ ]:
def make_args(out_dir, max_steps=-1, epochs=1):
    return SentenceTransformerTrainingArguments(output_dir=str(out_dir), num_train_epochs=epochs, max_steps=max_steps, per_device_train_batch_size=BATCH, learning_rate=LR, warmup_ratio=0.05, lr_scheduler_type="linear", batch_sampler=BatchSamplers.NO_DUPLICATES, dataloader_drop_last=True, logging_steps=10, save_strategy="steps", save_steps=40, save_total_limit=1, report_to="none", seed=0)

probe_n = BATCH * 3
probe_ds = Dataset.from_dict({"anchor": anchors[:probe_n], "positive": positives[:probe_n]})
loss = losses.CachedMultipleNegativesRankingLoss(model, scale=20.0, mini_batch_size=MINI_BATCH)

t = time.time()
SentenceTransformerTrainer(model=model, args=make_args(MODELS_DIR / "probe", max_steps=3), train_dataset=probe_ds, loss=loss).train()
sec_per_step = (time.time() - t) / 3
pairs_per_hour = BATCH / sec_per_step * 3600
print("секунд на шаг из", BATCH, "пар:", round(sec_per_step, 1))
print("пар в час:", round(pairs_per_hour))
N_TRAIN = int(min(len(anchors), pairs_per_hour * TARGET_HOURS))
N_TRAIN = N_TRAIN - N_TRAIN % BATCH
print("берем в эпоху", N_TRAIN, "пар из", len(anchors), "— это примерно", round(N_TRAIN / pairs_per_hour, 1), "часа")

The `warmup_ratio` argument is deprecated in Transformers v5+, and will also be removed from Sentence Transformers once support for Transformers v4 is dropped. Since you're using Transformers v5+, please use `warmup_steps` (as a float) to specify the warmup ratio instead.

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

/Users/amirhamidullin/PycharmProjects/avito_recsys/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

секунд на шаг из 256 пар: 18.1
пар в час: 51058
берем в эпоху 127488 пар из 459581 — это примерно 2.5 часа

## Обучение

Перемешиваем пары и берем столько, сколько влезает в бюджет времени. Одна эпоха: это дообучение а не обучение, и обучаемых эмбеддингов по id у нас нет, так что переобучаться после первой эпохи нечему

In [5]:
order = list(range(len(anchors)))
random.shuffle(order)
order = order[:N_TRAIN]
train_ds = Dataset.from_dict({"anchor": [anchors[i] for i in order], "positive": [positives[i] for i in order]})

t = time.time()
trainer = SentenceTransformerTrainer(model=model, args=make_args(MODELS_DIR / RUN_NAME), train_dataset=train_ds, loss=loss)
trainer.train()
print("обучение заняло", round((time.time() - t) / 3600, 2), "часа")

model.save(str(MODELS_DIR / RUN_NAME))
print("модель сохранена в", MODELS_DIR / RUN_NAME)

The `warmup_ratio` argument is deprecated in Transformers v5+, and will also be removed from Sentence Transformers once support for Transformers v4 is dropped. Since you're using Transformers v5+, please use `warmup_steps` (as a float) to specify the warmup ratio instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.46it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.28it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.28it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.09it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.09it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]

обучение заняло 3.77 часа

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.22it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.22it/s]

модель сохранена в ../data/models/user-bge-m3-ft1

## проверка

In [6]:
val = pl.read_parquet(PROC / "val_queries.parquet")
corpus = pl.read_parquet(PROC / "val_corpus.parquet")
item_ids = corpus["item_id"].to_list()
relevant = {q: set(r) for q, r in zip(val["query_id"], val["relevant"])}
is_seen = dict(zip(val["query_id"], val["is_seen"]))

sub_idx = np.load(PROC / "val_corpus_sub_idx.npy")   # то же подмножество, что во втором блокноте
sub_ids = [item_ids[j] for j in sub_idx]
print("подмножество корпуса:", len(sub_idx))

corpus_texts = [item_text(t, p, d) for t, p, d in zip(corpus["item_title_raw"], corpus["item_infm_params_text"], corpus["item_description_raw"])]
query_texts = [query_text(q, p) for q, p in zip(val["search_query"], val["search_infm_params_text"])]

def evaluate(corpus_emb, query_emb, label):
    idx = topk(query_emb, corpus_emb, k=200)
    pred = {q: [sub_ids[j] for j in row] for q, row in zip(val["query_id"], idx)}
    r50 = recall_at_k(pred, relevant, 50)
    by = recall_by_slice(pred, relevant, is_seen, 50)
    print(label, "-> recall@50:", round(r50, 4), " recall@200:", round(recall_at_k(pred, relevant, 200), 4), " (unseen", round(by[False][0], 3), " seen", round(by[True][0], 3), ")")
    return idx

# до обучения, из кэша
zs_path = PROC / "emb" / MODEL_KEY
if (zs_path / "val_corpus.npy").exists():
    zs_corpus = np.load(zs_path / "val_corpus_sub.npy")
    zs_query = np.load(zs_path / "val_queries.npy")
    _ = evaluate(zs_corpus, zs_query, "до обучения")

# после
model.eval()
model.half()
ft_corpus = encode(model, [corpus_texts[j] for j in sub_idx], batch_size=64, prefix=cfg["p"])
ft_query = encode(model, query_texts, batch_size=64, prefix=cfg["q"])
ft_idx = evaluate(ft_corpus, ft_query, "после обучения")

out = PROC / "emb" / RUN_NAME
out.mkdir(parents=True, exist_ok=True)
np.save(out / "val_corpus_sub.npy", ft_corpus)
np.save(out / "val_corpus_sub_idx.npy", sub_idx)
np.save(out / "val_queries.npy", ft_query)

подмножество корпуса: 47864

Batches:   0%|          | 0/748 [00:00<?, ?it/s]

Batches:   0%|          | 1/748 [00:02<25:25,  2.04s/it]

Batches:   0%|          | 2/748 [00:03<19:28,  1.57s/it]

Batches:   0%|          | 3/748 [00:04<17:16,  1.39s/it]

Batches:   1%|          | 4/748 [00:05<16:14,  1.31s/it]

Batches:   1%|          | 5/748 [00:06<15:39,  1.26s/it]

Batches:   1%|          | 6/748 [00:08<15:17,  1.24s/it]

Batches:   1%|          | 7/748 [00:09<15:03,  1.22s/it]

Batches:   1%|          | 8/748 [00:10<14:53,  1.21s/it]

Batches:   1%|          | 9/748 [00:11<14:47,  1.20s/it]

Batches:   1%|▏         | 10/748 [00:12<14:41,  1.20s/it]

Batches:   1%|▏         | 11/748 [00:13<14:38,  1.19s/it]

Batches:   2%|▏         | 12/748 [00:15<14:35,  1.19s/it]

Batches:   2%|▏         | 13/748 [00:16<14:32,  1.19s/it]

Batches:   2%|▏         | 14/748 [00:17<14:30,  1.19s/it]

Batches:   2%|▏         | 15/748 [00:18<14:28,  1.19s/it]

Batches:   2%|▏         | 16/748 [00:19<14:27,  1.19s/it]

Batches:   2%|▏         | 17/748 [00:21<14:27,  1.19s/it]

Batches:   2%|▏         | 18/748 [00:22<14:25,  1.19s/it]

Batches:   3%|▎         | 19/748 [00:23<14:24,  1.19s/it]

Batches:   3%|▎         | 20/748 [00:24<14:22,  1.18s/it]

Batches:   3%|▎         | 21/748 [00:25<14:21,  1.18s/it]

Batches:   3%|▎         | 22/748 [00:26<14:19,  1.18s/it]

Batches:   3%|▎         | 23/748 [00:28<14:18,  1.18s/it]

Batches:   3%|▎         | 24/748 [00:29<14:17,  1.18s/it]

Batches:   3%|▎         | 25/748 [00:30<14:16,  1.18s/it]

Batches:   3%|▎         | 26/748 [00:31<14:14,  1.18s/it]

Batches:   4%|▎         | 27/748 [00:32<14:13,  1.18s/it]

Batches:   4%|▎         | 28/748 [00:34<14:12,  1.18s/it]

Batches:   4%|▍         | 29/748 [00:35<14:10,  1.18s/it]

Batches:   4%|▍         | 30/748 [00:36<14:09,  1.18s/it]

Batches:   4%|▍         | 31/748 [00:37<14:08,  1.18s/it]

Batches:   4%|▍         | 32/748 [00:38<14:07,  1.18s/it]

Batches:   4%|▍         | 33/748 [00:39<14:06,  1.18s/it]

Batches:   5%|▍         | 34/748 [00:41<14:05,  1.18s/it]

Batches:   5%|▍         | 35/748 [00:42<14:03,  1.18s/it]

Batches:   5%|▍         | 36/748 [00:43<14:02,  1.18s/it]

Batches:   5%|▍         | 37/748 [00:44<14:01,  1.18s/it]

Batches:   5%|▌         | 38/748 [00:45<14:00,  1.18s/it]

Batches:   5%|▌         | 39/748 [00:47<13:58,  1.18s/it]

Batches:   5%|▌         | 40/748 [00:48<13:57,  1.18s/it]

Batches:   5%|▌         | 41/748 [00:49<13:56,  1.18s/it]

Batches:   6%|▌         | 42/748 [00:50<13:55,  1.18s/it]

Batches:   6%|▌         | 43/748 [00:51<13:54,  1.18s/it]

Batches:   6%|▌         | 44/748 [00:52<13:53,  1.18s/it]

Batches:   6%|▌         | 45/748 [00:54<13:51,  1.18s/it]

Batches:   6%|▌         | 46/748 [00:55<13:51,  1.18s/it]

Batches:   6%|▋         | 47/748 [00:56<13:49,  1.18s/it]

Batches:   6%|▋         | 48/748 [00:57<13:48,  1.18s/it]

Batches:   7%|▋         | 49/748 [00:58<13:47,  1.18s/it]

Batches:   7%|▋         | 50/748 [01:00<13:46,  1.18s/it]

Batches:   7%|▋         | 51/748 [01:01<13:44,  1.18s/it]

Batches:   7%|▋         | 52/748 [01:02<13:43,  1.18s/it]

Batches:   7%|▋         | 53/748 [01:03<13:42,  1.18s/it]

Batches:   7%|▋         | 54/748 [01:04<13:41,  1.18s/it]

Batches:   7%|▋         | 55/748 [01:06<13:40,  1.18s/it]

Batches:   7%|▋         | 56/748 [01:07<13:39,  1.18s/it]

Batches:   8%|▊         | 57/748 [01:08<13:37,  1.18s/it]

Batches:   8%|▊         | 58/748 [01:09<13:36,  1.18s/it]

Batches:   8%|▊         | 59/748 [01:10<13:35,  1.18s/it]

Batches:   8%|▊         | 60/748 [01:11<13:34,  1.18s/it]

Batches:   8%|▊         | 61/748 [01:13<13:33,  1.18s/it]

Batches:   8%|▊         | 62/748 [01:14<13:32,  1.18s/it]

Batches:   8%|▊         | 63/748 [01:15<13:31,  1.18s/it]

Batches:   9%|▊         | 64/748 [01:16<13:30,  1.18s/it]

Batches:   9%|▊         | 65/748 [01:17<13:29,  1.18s/it]

Batches:   9%|▉         | 66/748 [01:19<13:27,  1.18s/it]

Batches:   9%|▉         | 67/748 [01:20<13:26,  1.18s/it]

Batches:   9%|▉         | 68/748 [01:21<13:25,  1.18s/it]

Batches:   9%|▉         | 69/748 [01:22<13:24,  1.19s/it]

Batches:   9%|▉         | 70/748 [01:23<13:23,  1.19s/it]

Batches:   9%|▉         | 71/748 [01:24<13:22,  1.19s/it]

Batches:  10%|▉         | 72/748 [01:26<13:20,  1.18s/it]

Batches:  10%|▉         | 73/748 [01:27<13:19,  1.18s/it]

Batches:  10%|▉         | 74/748 [01:28<13:18,  1.18s/it]

Batches:  10%|█         | 75/748 [01:29<13:16,  1.18s/it]

Batches:  10%|█         | 76/748 [01:30<13:15,  1.18s/it]

Batches:  10%|█         | 77/748 [01:32<13:14,  1.18s/it]

Batches:  10%|█         | 78/748 [01:33<13:13,  1.18s/it]

Batches:  11%|█         | 79/748 [01:34<13:12,  1.18s/it]

Batches:  11%|█         | 80/748 [01:35<13:10,  1.18s/it]

Batches:  11%|█         | 81/748 [01:36<13:09,  1.18s/it]

Batches:  11%|█         | 82/748 [01:37<13:08,  1.18s/it]

Batches:  11%|█         | 83/748 [01:39<13:06,  1.18s/it]

Batches:  11%|█         | 84/748 [01:40<13:05,  1.18s/it]

Batches:  11%|█▏        | 85/748 [01:41<13:04,  1.18s/it]

Batches:  11%|█▏        | 86/748 [01:42<13:03,  1.18s/it]

Batches:  12%|█▏        | 87/748 [01:43<13:11,  1.20s/it]

Batches:  12%|█▏        | 88/748 [01:45<13:07,  1.19s/it]

Batches:  12%|█▏        | 89/748 [01:46<13:04,  1.19s/it]

Batches:  12%|█▏        | 90/748 [01:47<13:03,  1.19s/it]

Batches:  12%|█▏        | 91/748 [01:48<13:02,  1.19s/it]

Batches:  12%|█▏        | 92/748 [01:49<12:59,  1.19s/it]

Batches:  12%|█▏        | 93/748 [01:51<12:57,  1.19s/it]

Batches:  13%|█▎        | 94/748 [01:52<12:55,  1.19s/it]

Batches:  13%|█▎        | 95/748 [01:53<12:53,  1.18s/it]

Batches:  13%|█▎        | 96/748 [01:54<12:52,  1.18s/it]

Batches:  13%|█▎        | 97/748 [01:55<12:50,  1.18s/it]

Batches:  13%|█▎        | 98/748 [01:56<12:49,  1.18s/it]

Batches:  13%|█▎        | 99/748 [01:58<12:47,  1.18s/it]

Batches:  13%|█▎        | 100/748 [01:59<12:46,  1.18s/it]

Batches:  14%|█▎        | 101/748 [02:00<12:45,  1.18s/it]

Batches:  14%|█▎        | 102/748 [02:01<12:43,  1.18s/it]

Batches:  14%|█▍        | 103/748 [02:02<12:42,  1.18s/it]

Batches:  14%|█▍        | 104/748 [02:04<12:41,  1.18s/it]

Batches:  14%|█▍        | 105/748 [02:05<12:40,  1.18s/it]

Batches:  14%|█▍        | 106/748 [02:06<12:39,  1.18s/it]

Batches:  14%|█▍        | 107/748 [02:07<12:37,  1.18s/it]

Batches:  14%|█▍        | 108/748 [02:08<12:36,  1.18s/it]

Batches:  15%|█▍        | 109/748 [02:09<12:35,  1.18s/it]

Batches:  15%|█▍        | 110/748 [02:11<12:34,  1.18s/it]

Batches:  15%|█▍        | 111/748 [02:12<12:33,  1.18s/it]

Batches:  15%|█▍        | 112/748 [02:13<12:32,  1.18s/it]

Batches:  15%|█▌        | 113/748 [02:14<12:30,  1.18s/it]

Batches:  15%|█▌        | 114/748 [02:15<12:29,  1.18s/it]

Batches:  15%|█▌        | 115/748 [02:17<12:28,  1.18s/it]

Batches:  16%|█▌        | 116/748 [02:18<12:27,  1.18s/it]

Batches:  16%|█▌        | 117/748 [02:19<12:26,  1.18s/it]

Batches:  16%|█▌        | 118/748 [02:20<12:25,  1.18s/it]

Batches:  16%|█▌        | 119/748 [02:21<12:23,  1.18s/it]

Batches:  16%|█▌        | 120/748 [02:22<12:22,  1.18s/it]

Batches:  16%|█▌        | 121/748 [02:24<12:21,  1.18s/it]

Batches:  16%|█▋        | 122/748 [02:25<12:20,  1.18s/it]

Batches:  16%|█▋        | 123/748 [02:26<12:19,  1.18s/it]

Batches:  17%|█▋        | 124/748 [02:27<12:18,  1.18s/it]

Batches:  17%|█▋        | 125/748 [02:28<12:17,  1.18s/it]

Batches:  17%|█▋        | 126/748 [02:30<12:15,  1.18s/it]

Batches:  17%|█▋        | 127/748 [02:31<12:14,  1.18s/it]

Batches:  17%|█▋        | 128/748 [02:32<12:12,  1.18s/it]

Batches:  17%|█▋        | 129/748 [02:33<12:11,  1.18s/it]

Batches:  17%|█▋        | 130/748 [02:34<12:10,  1.18s/it]

Batches:  18%|█▊        | 131/748 [02:35<12:09,  1.18s/it]

Batches:  18%|█▊        | 132/748 [02:37<12:10,  1.19s/it]

Batches:  18%|█▊        | 133/748 [02:38<12:08,  1.19s/it]

Batches:  18%|█▊        | 134/748 [02:39<12:07,  1.18s/it]

Batches:  18%|█▊        | 135/748 [02:40<12:05,  1.18s/it]

Batches:  18%|█▊        | 136/748 [02:41<12:04,  1.18s/it]

Batches:  18%|█▊        | 137/748 [02:43<12:03,  1.18s/it]

Batches:  18%|█▊        | 138/748 [02:44<12:01,  1.18s/it]

Batches:  19%|█▊        | 139/748 [02:45<12:00,  1.18s/it]

Batches:  19%|█▊        | 140/748 [02:46<11:59,  1.18s/it]

Batches:  19%|█▉        | 141/748 [02:47<11:57,  1.18s/it]

Batches:  19%|█▉        | 142/748 [02:49<11:56,  1.18s/it]

Batches:  19%|█▉        | 143/748 [02:50<11:55,  1.18s/it]

Batches:  19%|█▉        | 144/748 [02:51<11:54,  1.18s/it]

Batches:  19%|█▉        | 145/748 [02:52<11:52,  1.18s/it]

Batches:  20%|█▉        | 146/748 [02:53<11:51,  1.18s/it]

Batches:  20%|█▉        | 147/748 [02:54<11:50,  1.18s/it]

Batches:  20%|█▉        | 148/748 [02:56<11:49,  1.18s/it]

Batches:  20%|█▉        | 149/748 [02:57<11:48,  1.18s/it]

Batches:  20%|██        | 150/748 [02:58<11:47,  1.18s/it]

Batches:  20%|██        | 151/748 [02:59<11:46,  1.18s/it]

Batches:  20%|██        | 152/748 [03:00<11:45,  1.18s/it]

Batches:  20%|██        | 153/748 [03:02<11:43,  1.18s/it]

Batches:  21%|██        | 154/748 [03:03<11:42,  1.18s/it]

Batches:  21%|██        | 155/748 [03:04<11:41,  1.18s/it]

Batches:  21%|██        | 156/748 [03:05<11:40,  1.18s/it]

Batches:  21%|██        | 157/748 [03:06<11:39,  1.18s/it]

Batches:  21%|██        | 158/748 [03:07<11:37,  1.18s/it]

Batches:  21%|██▏       | 159/748 [03:09<11:36,  1.18s/it]

Batches:  21%|██▏       | 160/748 [03:10<11:35,  1.18s/it]

Batches:  22%|██▏       | 161/748 [03:11<11:34,  1.18s/it]

Batches:  22%|██▏       | 162/748 [03:12<11:33,  1.18s/it]

Batches:  22%|██▏       | 163/748 [03:13<11:32,  1.18s/it]

Batches:  22%|██▏       | 164/748 [03:15<11:30,  1.18s/it]

Batches:  22%|██▏       | 165/748 [03:16<11:29,  1.18s/it]

Batches:  22%|██▏       | 166/748 [03:17<11:29,  1.19s/it]

Batches:  22%|██▏       | 167/748 [03:18<11:28,  1.18s/it]

Batches:  22%|██▏       | 168/748 [03:19<11:26,  1.18s/it]

Batches:  23%|██▎       | 169/748 [03:20<11:25,  1.18s/it]

Batches:  23%|██▎       | 170/748 [03:22<11:24,  1.18s/it]

Batches:  23%|██▎       | 171/748 [03:23<11:22,  1.18s/it]

Batches:  23%|██▎       | 172/748 [03:24<11:21,  1.18s/it]

Batches:  23%|██▎       | 173/748 [03:25<11:20,  1.18s/it]

Batches:  23%|██▎       | 174/748 [03:26<11:18,  1.18s/it]

Batches:  23%|██▎       | 175/748 [03:28<11:17,  1.18s/it]

Batches:  24%|██▎       | 176/748 [03:29<11:16,  1.18s/it]

Batches:  24%|██▎       | 177/748 [03:30<11:15,  1.18s/it]

Batches:  24%|██▍       | 178/748 [03:31<11:13,  1.18s/it]

Batches:  24%|██▍       | 179/748 [03:32<11:12,  1.18s/it]

Batches:  24%|██▍       | 180/748 [03:33<11:11,  1.18s/it]

Batches:  24%|██▍       | 181/748 [03:35<11:10,  1.18s/it]

Batches:  24%|██▍       | 182/748 [03:36<11:09,  1.18s/it]

Batches:  24%|██▍       | 183/748 [03:37<11:07,  1.18s/it]

Batches:  25%|██▍       | 184/748 [03:38<11:06,  1.18s/it]

Batches:  25%|██▍       | 185/748 [03:39<11:05,  1.18s/it]

Batches:  25%|██▍       | 186/748 [03:41<11:04,  1.18s/it]

Batches:  25%|██▌       | 187/748 [03:42<11:03,  1.18s/it]

Batches:  25%|██▌       | 188/748 [03:43<11:02,  1.18s/it]

Batches:  25%|██▌       | 189/748 [03:44<11:01,  1.18s/it]

Batches:  25%|██▌       | 190/748 [03:45<11:00,  1.18s/it]

Batches:  26%|██▌       | 191/748 [03:46<10:58,  1.18s/it]

Batches:  26%|██▌       | 192/748 [03:48<10:57,  1.18s/it]

Batches:  26%|██▌       | 193/748 [03:49<10:56,  1.18s/it]

Batches:  26%|██▌       | 194/748 [03:50<10:55,  1.18s/it]

Batches:  26%|██▌       | 195/748 [03:51<10:53,  1.18s/it]

Batches:  26%|██▌       | 196/748 [03:52<10:52,  1.18s/it]

Batches:  26%|██▋       | 197/748 [03:54<10:51,  1.18s/it]

Batches:  26%|██▋       | 198/748 [03:55<10:50,  1.18s/it]

Batches:  27%|██▋       | 199/748 [03:56<10:49,  1.18s/it]

Batches:  27%|██▋       | 200/748 [03:57<10:48,  1.18s/it]

Batches:  27%|██▋       | 201/748 [03:58<10:47,  1.18s/it]

Batches:  27%|██▋       | 202/748 [03:59<10:45,  1.18s/it]

Batches:  27%|██▋       | 203/748 [04:01<10:44,  1.18s/it]

Batches:  27%|██▋       | 204/748 [04:02<10:43,  1.18s/it]

Batches:  27%|██▋       | 205/748 [04:03<10:42,  1.18s/it]

Batches:  28%|██▊       | 206/748 [04:04<10:40,  1.18s/it]

Batches:  28%|██▊       | 207/748 [04:05<10:39,  1.18s/it]

Batches:  28%|██▊       | 208/748 [04:07<10:38,  1.18s/it]

Batches:  28%|██▊       | 209/748 [04:08<10:37,  1.18s/it]

Batches:  28%|██▊       | 210/748 [04:09<10:36,  1.18s/it]

Batches:  28%|██▊       | 211/748 [04:10<10:35,  1.18s/it]

Batches:  28%|██▊       | 212/748 [04:11<10:33,  1.18s/it]

Batches:  28%|██▊       | 213/748 [04:12<10:32,  1.18s/it]

Batches:  29%|██▊       | 214/748 [04:14<10:31,  1.18s/it]

Batches:  29%|██▊       | 215/748 [04:15<10:30,  1.18s/it]

Batches:  29%|██▉       | 216/748 [04:16<10:29,  1.18s/it]

Batches:  29%|██▉       | 217/748 [04:17<10:27,  1.18s/it]

Batches:  29%|██▉       | 218/748 [04:18<10:26,  1.18s/it]

Batches:  29%|██▉       | 219/748 [04:20<10:25,  1.18s/it]

Batches:  29%|██▉       | 220/748 [04:21<10:24,  1.18s/it]

Batches:  30%|██▉       | 221/748 [04:22<10:22,  1.18s/it]

Batches:  30%|██▉       | 222/748 [04:23<10:21,  1.18s/it]

Batches:  30%|██▉       | 223/748 [04:24<10:20,  1.18s/it]

Batches:  30%|██▉       | 224/748 [04:26<10:19,  1.18s/it]

Batches:  30%|███       | 225/748 [04:27<10:18,  1.18s/it]

Batches:  30%|███       | 226/748 [04:28<10:17,  1.18s/it]

Batches:  30%|███       | 227/748 [04:29<10:16,  1.18s/it]

Batches:  30%|███       | 228/748 [04:30<10:15,  1.18s/it]

Batches:  31%|███       | 229/748 [04:31<10:13,  1.18s/it]

Batches:  31%|███       | 230/748 [04:33<10:12,  1.18s/it]

Batches:  31%|███       | 231/748 [04:34<10:12,  1.18s/it]

Batches:  31%|███       | 232/748 [04:35<10:11,  1.18s/it]

Batches:  31%|███       | 233/748 [04:36<10:10,  1.18s/it]

Batches:  31%|███▏      | 234/748 [04:37<10:09,  1.19s/it]

Batches:  31%|███▏      | 235/748 [04:39<10:08,  1.19s/it]

Batches:  32%|███▏      | 236/748 [04:40<10:07,  1.19s/it]

Batches:  32%|███▏      | 237/748 [04:41<10:06,  1.19s/it]

Batches:  32%|███▏      | 238/748 [04:42<10:05,  1.19s/it]

Batches:  32%|███▏      | 239/748 [04:43<10:03,  1.19s/it]

Batches:  32%|███▏      | 240/748 [04:44<10:02,  1.19s/it]

Batches:  32%|███▏      | 241/748 [04:46<10:01,  1.19s/it]

Batches:  32%|███▏      | 242/748 [04:47<10:00,  1.19s/it]

Batches:  32%|███▏      | 243/748 [04:48<09:59,  1.19s/it]

Batches:  33%|███▎      | 244/748 [04:49<09:58,  1.19s/it]

Batches:  33%|███▎      | 245/748 [04:50<09:57,  1.19s/it]

Batches:  33%|███▎      | 246/748 [04:52<09:56,  1.19s/it]

Batches:  33%|███▎      | 247/748 [04:53<09:55,  1.19s/it]

Batches:  33%|███▎      | 248/748 [04:54<09:53,  1.19s/it]

Batches:  33%|███▎      | 249/748 [04:55<09:52,  1.19s/it]

Batches:  33%|███▎      | 250/748 [04:56<09:51,  1.19s/it]

Batches:  34%|███▎      | 251/748 [04:58<09:50,  1.19s/it]

Batches:  34%|███▎      | 252/748 [04:59<09:49,  1.19s/it]

Batches:  34%|███▍      | 253/748 [05:00<09:48,  1.19s/it]

Batches:  34%|███▍      | 254/748 [05:01<09:46,  1.19s/it]

Batches:  34%|███▍      | 255/748 [05:02<09:45,  1.19s/it]

Batches:  34%|███▍      | 256/748 [05:03<09:44,  1.19s/it]

Batches:  34%|███▍      | 257/748 [05:05<09:43,  1.19s/it]

Batches:  34%|███▍      | 258/748 [05:06<09:42,  1.19s/it]

Batches:  35%|███▍      | 259/748 [05:07<09:41,  1.19s/it]

Batches:  35%|███▍      | 260/748 [05:08<09:40,  1.19s/it]

Batches:  35%|███▍      | 261/748 [05:09<09:39,  1.19s/it]

Batches:  35%|███▌      | 262/748 [05:11<09:38,  1.19s/it]

Batches:  35%|███▌      | 263/748 [05:12<09:37,  1.19s/it]

Batches:  35%|███▌      | 264/748 [05:13<09:36,  1.19s/it]

Batches:  35%|███▌      | 265/748 [05:14<09:35,  1.19s/it]

Batches:  36%|███▌      | 266/748 [05:15<09:34,  1.19s/it]

Batches:  36%|███▌      | 267/748 [05:17<09:33,  1.19s/it]

Batches:  36%|███▌      | 268/748 [05:18<09:32,  1.19s/it]

Batches:  36%|███▌      | 269/748 [05:19<09:32,  1.20s/it]

Batches:  36%|███▌      | 270/748 [05:20<09:31,  1.20s/it]

Batches:  36%|███▌      | 271/748 [05:21<09:30,  1.20s/it]

Batches:  36%|███▋      | 272/748 [05:23<09:29,  1.20s/it]

Batches:  36%|███▋      | 273/748 [05:24<09:27,  1.19s/it]

Batches:  37%|███▋      | 274/748 [05:25<09:26,  1.19s/it]

Batches:  37%|███▋      | 275/748 [05:26<09:24,  1.19s/it]

Batches:  37%|███▋      | 276/748 [05:27<09:23,  1.19s/it]

Batches:  37%|███▋      | 277/748 [05:29<09:22,  1.19s/it]

Batches:  37%|███▋      | 278/748 [05:30<09:21,  1.20s/it]

Batches:  37%|███▋      | 279/748 [05:31<09:20,  1.20s/it]

Batches:  37%|███▋      | 280/748 [05:32<09:19,  1.20s/it]

Batches:  38%|███▊      | 281/748 [05:33<09:18,  1.20s/it]

Batches:  38%|███▊      | 282/748 [05:35<09:18,  1.20s/it]

Batches:  38%|███▊      | 283/748 [05:36<09:17,  1.20s/it]

Batches:  38%|███▊      | 284/748 [05:37<09:15,  1.20s/it]

Batches:  38%|███▊      | 285/748 [05:38<09:14,  1.20s/it]

Batches:  38%|███▊      | 286/748 [05:39<09:13,  1.20s/it]

Batches:  38%|███▊      | 287/748 [05:41<09:12,  1.20s/it]

Batches:  39%|███▊      | 288/748 [05:42<09:11,  1.20s/it]

Batches:  39%|███▊      | 289/748 [05:43<09:10,  1.20s/it]

Batches:  39%|███▉      | 290/748 [05:44<09:08,  1.20s/it]

Batches:  39%|███▉      | 291/748 [05:45<09:07,  1.20s/it]

Batches:  39%|███▉      | 292/748 [05:46<09:06,  1.20s/it]

Batches:  39%|███▉      | 293/748 [05:48<09:05,  1.20s/it]

Batches:  39%|███▉      | 294/748 [05:49<09:04,  1.20s/it]

Batches:  39%|███▉      | 295/748 [05:50<09:03,  1.20s/it]

Batches:  40%|███▉      | 296/748 [05:51<09:02,  1.20s/it]

Batches:  40%|███▉      | 297/748 [05:52<09:01,  1.20s/it]

Batches:  40%|███▉      | 298/748 [05:54<09:00,  1.20s/it]

Batches:  40%|███▉      | 299/748 [05:55<08:58,  1.20s/it]

Batches:  40%|████      | 300/748 [05:56<08:57,  1.20s/it]

Batches:  40%|████      | 301/748 [05:57<08:56,  1.20s/it]

Batches:  40%|████      | 302/748 [05:58<08:54,  1.20s/it]

Batches:  41%|████      | 303/748 [06:00<08:54,  1.20s/it]

Batches:  41%|████      | 304/748 [06:01<08:53,  1.20s/it]

Batches:  41%|████      | 305/748 [06:02<08:52,  1.20s/it]

Batches:  41%|████      | 306/748 [06:03<08:50,  1.20s/it]

Batches:  41%|████      | 307/748 [06:04<08:49,  1.20s/it]

Batches:  41%|████      | 308/748 [06:06<08:47,  1.20s/it]

Batches:  41%|████▏     | 309/748 [06:07<08:46,  1.20s/it]

Batches:  41%|████▏     | 310/748 [06:08<08:45,  1.20s/it]

Batches:  42%|████▏     | 311/748 [06:09<08:44,  1.20s/it]

Batches:  42%|████▏     | 312/748 [06:10<08:42,  1.20s/it]

Batches:  42%|████▏     | 313/748 [06:12<08:41,  1.20s/it]

Batches:  42%|████▏     | 314/748 [06:13<08:40,  1.20s/it]

Batches:  42%|████▏     | 315/748 [06:14<08:39,  1.20s/it]

Batches:  42%|████▏     | 316/748 [06:15<08:38,  1.20s/it]

Batches:  42%|████▏     | 317/748 [06:16<08:37,  1.20s/it]

Batches:  43%|████▎     | 318/748 [06:18<08:36,  1.20s/it]

Batches:  43%|████▎     | 319/748 [06:19<08:34,  1.20s/it]

Batches:  43%|████▎     | 320/748 [06:20<08:33,  1.20s/it]

Batches:  43%|████▎     | 321/748 [06:21<08:32,  1.20s/it]

Batches:  43%|████▎     | 322/748 [06:23<08:31,  1.20s/it]

Batches:  43%|████▎     | 323/748 [06:24<08:30,  1.20s/it]

Batches:  43%|████▎     | 324/748 [06:25<08:29,  1.20s/it]

Batches:  43%|████▎     | 325/748 [06:26<08:28,  1.20s/it]

Batches:  44%|████▎     | 326/748 [06:27<08:27,  1.20s/it]

Batches:  44%|████▎     | 327/748 [06:29<08:25,  1.20s/it]

Batches:  44%|████▍     | 328/748 [06:30<08:24,  1.20s/it]

Batches:  44%|████▍     | 329/748 [06:31<08:23,  1.20s/it]

Batches:  44%|████▍     | 330/748 [06:32<08:22,  1.20s/it]

Batches:  44%|████▍     | 331/748 [06:33<08:21,  1.20s/it]

Batches:  44%|████▍     | 332/748 [06:35<08:20,  1.20s/it]

Batches:  45%|████▍     | 333/748 [06:36<08:18,  1.20s/it]

Batches:  45%|████▍     | 334/748 [06:37<08:17,  1.20s/it]

Batches:  45%|████▍     | 335/748 [06:38<08:17,  1.20s/it]

Batches:  45%|████▍     | 336/748 [06:39<08:16,  1.20s/it]

Batches:  45%|████▌     | 337/748 [06:41<08:15,  1.21s/it]

Batches:  45%|████▌     | 338/748 [06:42<08:14,  1.21s/it]

Batches:  45%|████▌     | 339/748 [06:43<08:13,  1.21s/it]

Batches:  45%|████▌     | 340/748 [06:44<08:12,  1.21s/it]

Batches:  46%|████▌     | 341/748 [06:45<08:11,  1.21s/it]

Batches:  46%|████▌     | 342/748 [06:47<08:10,  1.21s/it]

Batches:  46%|████▌     | 343/748 [06:48<08:09,  1.21s/it]

Batches:  46%|████▌     | 344/748 [06:49<08:08,  1.21s/it]

Batches:  46%|████▌     | 345/748 [06:50<08:06,  1.21s/it]

Batches:  46%|████▋     | 346/748 [06:51<08:04,  1.21s/it]

Batches:  46%|████▋     | 347/748 [06:53<08:03,  1.20s/it]

Batches:  47%|████▋     | 348/748 [06:54<08:01,  1.20s/it]

Batches:  47%|████▋     | 349/748 [06:55<08:00,  1.20s/it]

Batches:  47%|████▋     | 350/748 [06:56<07:59,  1.21s/it]

Batches:  47%|████▋     | 351/748 [06:57<07:59,  1.21s/it]

Batches:  47%|████▋     | 352/748 [06:59<07:57,  1.21s/it]

Batches:  47%|████▋     | 353/748 [07:00<07:56,  1.21s/it]

Batches:  47%|████▋     | 354/748 [07:01<07:54,  1.20s/it]

Batches:  47%|████▋     | 355/748 [07:02<07:53,  1.20s/it]

Batches:  48%|████▊     | 356/748 [07:03<07:51,  1.20s/it]

Batches:  48%|████▊     | 357/748 [07:05<07:50,  1.20s/it]

Batches:  48%|████▊     | 358/748 [07:06<07:49,  1.20s/it]

Batches:  48%|████▊     | 359/748 [07:07<07:48,  1.20s/it]

Batches:  48%|████▊     | 360/748 [07:08<07:46,  1.20s/it]

Batches:  48%|████▊     | 361/748 [07:09<07:45,  1.20s/it]

Batches:  48%|████▊     | 362/748 [07:11<07:44,  1.20s/it]

Batches:  49%|████▊     | 363/748 [07:12<07:43,  1.20s/it]

Batches:  49%|████▊     | 364/748 [07:13<07:42,  1.20s/it]

Batches:  49%|████▉     | 365/748 [07:14<07:41,  1.21s/it]

Batches:  49%|████▉     | 366/748 [07:16<07:40,  1.21s/it]

Batches:  49%|████▉     | 367/748 [07:17<07:39,  1.21s/it]

Batches:  49%|████▉     | 368/748 [07:18<07:38,  1.21s/it]

Batches:  49%|████▉     | 369/748 [07:19<07:37,  1.21s/it]

Batches:  49%|████▉     | 370/748 [07:20<07:38,  1.21s/it]

Batches:  50%|████▉     | 371/748 [07:22<07:37,  1.21s/it]

Batches:  50%|████▉     | 372/748 [07:23<07:36,  1.21s/it]

Batches:  50%|████▉     | 373/748 [07:24<07:34,  1.21s/it]

Batches:  50%|█████     | 374/748 [07:25<07:32,  1.21s/it]

Batches:  50%|█████     | 375/748 [07:26<07:31,  1.21s/it]

Batches:  50%|█████     | 376/748 [07:28<07:31,  1.21s/it]

Batches:  50%|█████     | 377/748 [07:29<07:30,  1.21s/it]

Batches:  51%|█████     | 378/748 [07:30<07:28,  1.21s/it]

Batches:  51%|█████     | 379/748 [07:31<07:27,  1.21s/it]

Batches:  51%|█████     | 380/748 [07:32<07:25,  1.21s/it]

Batches:  51%|█████     | 381/748 [07:34<07:24,  1.21s/it]

Batches:  51%|█████     | 382/748 [07:35<07:23,  1.21s/it]

Batches:  51%|█████     | 383/748 [07:36<07:22,  1.21s/it]

Batches:  51%|█████▏    | 384/748 [07:37<07:20,  1.21s/it]

Batches:  51%|█████▏    | 385/748 [07:39<07:20,  1.21s/it]

Batches:  52%|█████▏    | 386/748 [07:40<07:18,  1.21s/it]

Batches:  52%|█████▏    | 387/748 [07:41<07:17,  1.21s/it]

Batches:  52%|█████▏    | 388/748 [07:42<07:16,  1.21s/it]

Batches:  52%|█████▏    | 389/748 [07:43<07:15,  1.21s/it]

Batches:  52%|█████▏    | 390/748 [07:45<07:14,  1.21s/it]

Batches:  52%|█████▏    | 391/748 [07:46<07:13,  1.22s/it]

Batches:  52%|█████▏    | 392/748 [07:47<07:12,  1.21s/it]

Batches:  53%|█████▎    | 393/748 [07:48<07:10,  1.21s/it]

Batches:  53%|█████▎    | 394/748 [07:49<07:09,  1.21s/it]

Batches:  53%|█████▎    | 395/748 [07:51<07:08,  1.21s/it]

Batches:  53%|█████▎    | 396/748 [07:52<07:07,  1.21s/it]

Batches:  53%|█████▎    | 397/748 [07:53<07:06,  1.21s/it]

Batches:  53%|█████▎    | 398/748 [07:54<07:05,  1.21s/it]

Batches:  53%|█████▎    | 399/748 [07:56<07:04,  1.22s/it]

Batches:  53%|█████▎    | 400/748 [07:57<07:03,  1.22s/it]

Batches:  54%|█████▎    | 401/748 [07:58<07:02,  1.22s/it]

Batches:  54%|█████▎    | 402/748 [07:59<07:01,  1.22s/it]

Batches:  54%|█████▍    | 403/748 [08:00<06:59,  1.22s/it]

Batches:  54%|█████▍    | 404/748 [08:02<06:58,  1.22s/it]

Batches:  54%|█████▍    | 405/748 [08:03<06:57,  1.22s/it]

Batches:  54%|█████▍    | 406/748 [08:04<06:56,  1.22s/it]

Batches:  54%|█████▍    | 407/748 [08:05<06:55,  1.22s/it]

Batches:  55%|█████▍    | 408/748 [08:07<06:54,  1.22s/it]

Batches:  55%|█████▍    | 409/748 [08:08<06:52,  1.22s/it]

Batches:  55%|█████▍    | 410/748 [08:09<06:51,  1.22s/it]

Batches:  55%|█████▍    | 411/748 [08:10<06:50,  1.22s/it]

Batches:  55%|█████▌    | 412/748 [08:11<06:49,  1.22s/it]

Batches:  55%|█████▌    | 413/748 [08:13<06:48,  1.22s/it]

Batches:  55%|█████▌    | 414/748 [08:14<06:47,  1.22s/it]

Batches:  55%|█████▌    | 415/748 [08:15<06:46,  1.22s/it]

Batches:  56%|█████▌    | 416/748 [08:16<06:45,  1.22s/it]

Batches:  56%|█████▌    | 417/748 [08:17<06:44,  1.22s/it]

Batches:  56%|█████▌    | 418/748 [08:19<06:43,  1.22s/it]

Batches:  56%|█████▌    | 419/748 [08:20<06:42,  1.22s/it]

Batches:  56%|█████▌    | 420/748 [08:21<06:40,  1.22s/it]

Batches:  56%|█████▋    | 421/748 [08:22<06:39,  1.22s/it]

Batches:  56%|█████▋    | 422/748 [08:24<06:38,  1.22s/it]

Batches:  57%|█████▋    | 423/748 [08:25<06:37,  1.22s/it]

Batches:  57%|█████▋    | 424/748 [08:26<06:36,  1.22s/it]

Batches:  57%|█████▋    | 425/748 [08:27<06:34,  1.22s/it]

Batches:  57%|█████▋    | 426/748 [08:28<06:33,  1.22s/it]

Batches:  57%|█████▋    | 427/748 [08:30<06:32,  1.22s/it]

Batches:  57%|█████▋    | 428/748 [08:31<06:31,  1.22s/it]

Batches:  57%|█████▋    | 429/748 [08:32<06:30,  1.22s/it]

Batches:  57%|█████▋    | 430/748 [08:33<06:29,  1.22s/it]

Batches:  58%|█████▊    | 431/748 [08:35<06:28,  1.22s/it]

Batches:  58%|█████▊    | 432/748 [08:36<06:26,  1.22s/it]

Batches:  58%|█████▊    | 433/748 [08:37<06:25,  1.23s/it]

Batches:  58%|█████▊    | 434/748 [08:38<06:25,  1.23s/it]

Batches:  58%|█████▊    | 435/748 [08:40<06:23,  1.23s/it]

Batches:  58%|█████▊    | 436/748 [08:41<06:22,  1.23s/it]

Batches:  58%|█████▊    | 437/748 [08:42<06:21,  1.23s/it]

Batches:  59%|█████▊    | 438/748 [08:43<06:20,  1.23s/it]

Batches:  59%|█████▊    | 439/748 [08:44<06:18,  1.23s/it]

Batches:  59%|█████▉    | 440/748 [08:46<06:17,  1.23s/it]

Batches:  59%|█████▉    | 441/748 [08:47<06:16,  1.23s/it]

Batches:  59%|█████▉    | 442/748 [08:48<06:15,  1.23s/it]

Batches:  59%|█████▉    | 443/748 [08:49<06:14,  1.23s/it]

Batches:  59%|█████▉    | 444/748 [08:51<06:12,  1.23s/it]

Batches:  59%|█████▉    | 445/748 [08:52<06:11,  1.23s/it]

Batches:  60%|█████▉    | 446/748 [08:53<06:10,  1.23s/it]

Batches:  60%|█████▉    | 447/748 [08:54<06:11,  1.23s/it]

Batches:  60%|█████▉    | 448/748 [08:56<06:31,  1.30s/it]

Batches:  60%|██████    | 449/748 [08:57<06:26,  1.29s/it]

Batches:  60%|██████    | 450/748 [08:58<06:20,  1.28s/it]

Batches:  60%|██████    | 451/748 [08:59<06:14,  1.26s/it]

Batches:  60%|██████    | 452/748 [09:01<06:11,  1.25s/it]

Batches:  61%|██████    | 453/748 [09:02<06:09,  1.25s/it]

Batches:  61%|██████    | 454/748 [09:03<06:07,  1.25s/it]

Batches:  61%|██████    | 455/748 [09:04<06:05,  1.25s/it]

Batches:  61%|██████    | 456/748 [09:06<06:03,  1.25s/it]

Batches:  61%|██████    | 457/748 [09:07<06:01,  1.24s/it]

Batches:  61%|██████    | 458/748 [09:08<05:59,  1.24s/it]

Batches:  61%|██████▏   | 459/748 [09:09<05:57,  1.24s/it]

Batches:  61%|██████▏   | 460/748 [09:11<05:57,  1.24s/it]

Batches:  62%|██████▏   | 461/748 [09:12<05:59,  1.25s/it]

Batches:  62%|██████▏   | 462/748 [09:13<05:59,  1.26s/it]

Batches:  62%|██████▏   | 463/748 [09:14<05:57,  1.26s/it]

Batches:  62%|██████▏   | 464/748 [09:16<05:55,  1.25s/it]

Batches:  62%|██████▏   | 465/748 [09:17<05:52,  1.25s/it]

Batches:  62%|██████▏   | 466/748 [09:18<05:50,  1.24s/it]

Batches:  62%|██████▏   | 467/748 [09:19<05:47,  1.24s/it]

Batches:  63%|██████▎   | 468/748 [09:21<05:45,  1.24s/it]

Batches:  63%|██████▎   | 469/748 [09:22<05:44,  1.23s/it]

Batches:  63%|██████▎   | 470/748 [09:23<05:42,  1.23s/it]

Batches:  63%|██████▎   | 471/748 [09:24<05:41,  1.23s/it]

Batches:  63%|██████▎   | 472/748 [09:26<05:39,  1.23s/it]

Batches:  63%|██████▎   | 473/748 [09:27<05:38,  1.23s/it]

Batches:  63%|██████▎   | 474/748 [09:28<05:37,  1.23s/it]

Batches:  64%|██████▎   | 475/748 [09:29<05:35,  1.23s/it]

Batches:  64%|██████▎   | 476/748 [09:30<05:34,  1.23s/it]

Batches:  64%|██████▍   | 477/748 [09:32<05:33,  1.23s/it]

Batches:  64%|██████▍   | 478/748 [09:33<05:32,  1.23s/it]

Batches:  64%|██████▍   | 479/748 [09:34<05:31,  1.23s/it]

Batches:  64%|██████▍   | 480/748 [09:35<05:30,  1.23s/it]

Batches:  64%|██████▍   | 481/748 [09:37<05:29,  1.23s/it]

Batches:  64%|██████▍   | 482/748 [09:38<05:27,  1.23s/it]

Batches:  65%|██████▍   | 483/748 [09:39<05:26,  1.23s/it]

Batches:  65%|██████▍   | 484/748 [09:40<05:24,  1.23s/it]

Batches:  65%|██████▍   | 485/748 [09:42<05:23,  1.23s/it]

Batches:  65%|██████▍   | 486/748 [09:43<05:22,  1.23s/it]

Batches:  65%|██████▌   | 487/748 [09:44<05:20,  1.23s/it]

Batches:  65%|██████▌   | 488/748 [09:45<05:19,  1.23s/it]

Batches:  65%|██████▌   | 489/748 [09:46<05:18,  1.23s/it]

Batches:  66%|██████▌   | 490/748 [09:48<05:17,  1.23s/it]

Batches:  66%|██████▌   | 491/748 [09:49<05:16,  1.23s/it]

Batches:  66%|██████▌   | 492/748 [09:50<05:15,  1.23s/it]

Batches:  66%|██████▌   | 493/748 [09:51<05:13,  1.23s/it]

Batches:  66%|██████▌   | 494/748 [09:53<05:12,  1.23s/it]

Batches:  66%|██████▌   | 495/748 [09:54<05:10,  1.23s/it]

Batches:  66%|██████▋   | 496/748 [09:55<05:09,  1.23s/it]

Batches:  66%|██████▋   | 497/748 [09:56<05:08,  1.23s/it]

Batches:  67%|██████▋   | 498/748 [09:57<05:07,  1.23s/it]

Batches:  67%|██████▋   | 499/748 [09:59<05:06,  1.23s/it]

Batches:  67%|██████▋   | 500/748 [10:00<05:05,  1.23s/it]

Batches:  67%|██████▋   | 501/748 [10:01<05:03,  1.23s/it]

Batches:  67%|██████▋   | 502/748 [10:02<05:02,  1.23s/it]

Batches:  67%|██████▋   | 503/748 [10:04<05:00,  1.23s/it]

Batches:  67%|██████▋   | 504/748 [10:05<04:59,  1.23s/it]

Batches:  68%|██████▊   | 505/748 [10:06<04:58,  1.23s/it]

Batches:  68%|██████▊   | 506/748 [10:07<04:56,  1.23s/it]

Batches:  68%|██████▊   | 507/748 [10:09<04:55,  1.23s/it]

Batches:  68%|██████▊   | 508/748 [10:10<04:54,  1.23s/it]

Batches:  68%|██████▊   | 509/748 [10:11<04:53,  1.23s/it]

Batches:  68%|██████▊   | 510/748 [10:12<04:52,  1.23s/it]

Batches:  68%|██████▊   | 511/748 [10:13<04:51,  1.23s/it]

Batches:  68%|██████▊   | 512/748 [10:15<04:49,  1.23s/it]

Batches:  69%|██████▊   | 513/748 [10:16<04:48,  1.23s/it]

Batches:  69%|██████▊   | 514/748 [10:17<04:47,  1.23s/it]

Batches:  69%|██████▉   | 515/748 [10:18<04:46,  1.23s/it]

Batches:  69%|██████▉   | 516/748 [10:20<04:45,  1.23s/it]

Batches:  69%|██████▉   | 517/748 [10:21<04:44,  1.23s/it]

Batches:  69%|██████▉   | 518/748 [10:22<04:42,  1.23s/it]

Batches:  69%|██████▉   | 519/748 [10:23<04:41,  1.23s/it]

Batches:  70%|██████▉   | 520/748 [10:25<04:39,  1.23s/it]

Batches:  70%|██████▉   | 521/748 [10:26<04:38,  1.23s/it]

Batches:  70%|██████▉   | 522/748 [10:27<04:36,  1.23s/it]

Batches:  70%|██████▉   | 523/748 [10:28<04:35,  1.22s/it]

Batches:  70%|███████   | 524/748 [10:29<04:34,  1.23s/it]

Batches:  70%|███████   | 525/748 [10:31<04:33,  1.23s/it]

Batches:  70%|███████   | 526/748 [10:32<04:31,  1.22s/it]

Batches:  70%|███████   | 527/748 [10:33<04:30,  1.23s/it]

Batches:  71%|███████   | 528/748 [10:34<04:29,  1.23s/it]

Batches:  71%|███████   | 529/748 [10:36<04:28,  1.23s/it]

Batches:  71%|███████   | 530/748 [10:37<04:27,  1.23s/it]

Batches:  71%|███████   | 531/748 [10:38<04:25,  1.23s/it]

Batches:  71%|███████   | 532/748 [10:39<04:24,  1.22s/it]

Batches:  71%|███████▏  | 533/748 [10:40<04:23,  1.23s/it]

Batches:  71%|███████▏  | 534/748 [10:42<04:22,  1.23s/it]

Batches:  72%|███████▏  | 535/748 [10:43<04:21,  1.23s/it]

Batches:  72%|███████▏  | 536/748 [10:44<04:19,  1.23s/it]

Batches:  72%|███████▏  | 537/748 [10:45<04:18,  1.22s/it]

Batches:  72%|███████▏  | 538/748 [10:47<04:18,  1.23s/it]

Batches:  72%|███████▏  | 539/748 [10:48<04:18,  1.24s/it]

Batches:  72%|███████▏  | 540/748 [10:49<04:17,  1.24s/it]

Batches:  72%|███████▏  | 541/748 [10:50<04:15,  1.23s/it]

Batches:  72%|███████▏  | 542/748 [10:52<04:13,  1.23s/it]

Batches:  73%|███████▎  | 543/748 [10:53<04:11,  1.23s/it]

Batches:  73%|███████▎  | 544/748 [10:54<04:10,  1.23s/it]

Batches:  73%|███████▎  | 545/748 [10:55<04:08,  1.22s/it]

Batches:  73%|███████▎  | 546/748 [10:56<04:07,  1.22s/it]

Batches:  73%|███████▎  | 547/748 [10:58<04:06,  1.22s/it]

Batches:  73%|███████▎  | 548/748 [10:59<04:04,  1.22s/it]

Batches:  73%|███████▎  | 549/748 [11:00<04:03,  1.22s/it]

Batches:  74%|███████▎  | 550/748 [11:01<04:02,  1.22s/it]

Batches:  74%|███████▎  | 551/748 [11:03<04:00,  1.22s/it]

Batches:  74%|███████▍  | 552/748 [11:04<03:59,  1.22s/it]

Batches:  74%|███████▍  | 553/748 [11:05<03:58,  1.22s/it]

Batches:  74%|███████▍  | 554/748 [11:06<03:57,  1.22s/it]

Batches:  74%|███████▍  | 555/748 [11:07<03:55,  1.22s/it]

Batches:  74%|███████▍  | 556/748 [11:09<03:54,  1.22s/it]

Batches:  74%|███████▍  | 557/748 [11:10<03:53,  1.22s/it]

Batches:  75%|███████▍  | 558/748 [11:11<03:52,  1.22s/it]

Batches:  75%|███████▍  | 559/748 [11:12<03:50,  1.22s/it]

Batches:  75%|███████▍  | 560/748 [11:14<03:49,  1.22s/it]

Batches:  75%|███████▌  | 561/748 [11:15<03:47,  1.22s/it]

Batches:  75%|███████▌  | 562/748 [11:16<03:45,  1.21s/it]

Batches:  75%|███████▌  | 563/748 [11:17<03:43,  1.21s/it]

Batches:  75%|███████▌  | 564/748 [11:18<03:41,  1.20s/it]

Batches:  76%|███████▌  | 565/748 [11:20<03:39,  1.20s/it]

Batches:  76%|███████▌  | 566/748 [11:21<03:38,  1.20s/it]

Batches:  76%|███████▌  | 567/748 [11:22<03:36,  1.20s/it]

Batches:  76%|███████▌  | 568/748 [11:23<03:35,  1.20s/it]

Batches:  76%|███████▌  | 569/748 [11:24<03:35,  1.20s/it]

Batches:  76%|███████▌  | 570/748 [11:26<03:33,  1.20s/it]

Batches:  76%|███████▋  | 571/748 [11:27<03:32,  1.20s/it]

Batches:  76%|███████▋  | 572/748 [11:28<03:31,  1.20s/it]

Batches:  77%|███████▋  | 573/748 [11:29<03:29,  1.20s/it]

Batches:  77%|███████▋  | 574/748 [11:30<03:27,  1.20s/it]

Batches:  77%|███████▋  | 575/748 [11:31<03:26,  1.19s/it]

Batches:  77%|███████▋  | 576/748 [11:33<03:25,  1.19s/it]

Batches:  77%|███████▋  | 577/748 [11:34<03:24,  1.19s/it]

Batches:  77%|███████▋  | 578/748 [11:35<03:22,  1.19s/it]

Batches:  77%|███████▋  | 579/748 [11:36<03:21,  1.19s/it]

Batches:  78%|███████▊  | 580/748 [11:37<03:20,  1.19s/it]

Batches:  78%|███████▊  | 581/748 [11:39<03:19,  1.19s/it]

Batches:  78%|███████▊  | 582/748 [11:40<03:18,  1.19s/it]

Batches:  78%|███████▊  | 583/748 [11:41<03:16,  1.19s/it]

Batches:  78%|███████▊  | 584/748 [11:42<03:15,  1.19s/it]

Batches:  78%|███████▊  | 585/748 [11:43<03:14,  1.19s/it]

Batches:  78%|███████▊  | 586/748 [11:45<03:13,  1.20s/it]

Batches:  78%|███████▊  | 587/748 [11:46<03:13,  1.20s/it]

Batches:  79%|███████▊  | 588/748 [11:47<03:13,  1.21s/it]

Batches:  79%|███████▊  | 589/748 [11:48<03:14,  1.23s/it]

Batches:  79%|███████▉  | 590/748 [11:50<03:13,  1.22s/it]

Batches:  79%|███████▉  | 591/748 [11:51<03:11,  1.22s/it]

Batches:  79%|███████▉  | 592/748 [11:52<03:08,  1.21s/it]

Batches:  79%|███████▉  | 593/748 [11:53<03:06,  1.20s/it]

Batches:  79%|███████▉  | 594/748 [11:54<03:04,  1.20s/it]

Batches:  80%|███████▉  | 595/748 [11:56<03:03,  1.20s/it]

Batches:  80%|███████▉  | 596/748 [11:57<03:01,  1.20s/it]

Batches:  80%|███████▉  | 597/748 [11:58<03:01,  1.20s/it]

Batches:  80%|███████▉  | 598/748 [11:59<03:00,  1.20s/it]

Batches:  80%|████████  | 599/748 [12:00<02:58,  1.20s/it]

Batches:  80%|████████  | 600/748 [12:01<02:56,  1.19s/it]

Batches:  80%|████████  | 601/748 [12:03<02:55,  1.19s/it]

Batches:  80%|████████  | 602/748 [12:04<02:54,  1.19s/it]

Batches:  81%|████████  | 603/748 [12:05<02:52,  1.19s/it]

Batches:  81%|████████  | 604/748 [12:06<02:51,  1.19s/it]

Batches:  81%|████████  | 605/748 [12:07<02:50,  1.19s/it]

Batches:  81%|████████  | 606/748 [12:09<02:49,  1.19s/it]

Batches:  81%|████████  | 607/748 [12:10<02:48,  1.19s/it]

Batches:  81%|████████▏ | 608/748 [12:11<02:46,  1.19s/it]

Batches:  81%|████████▏ | 609/748 [12:12<02:45,  1.19s/it]

Batches:  82%|████████▏ | 610/748 [12:13<02:44,  1.19s/it]

Batches:  82%|████████▏ | 611/748 [12:15<02:43,  1.19s/it]

Batches:  82%|████████▏ | 612/748 [12:16<02:41,  1.19s/it]

Batches:  82%|████████▏ | 613/748 [12:17<02:39,  1.18s/it]

Batches:  82%|████████▏ | 614/748 [12:18<02:37,  1.18s/it]

Batches:  82%|████████▏ | 615/748 [12:19<02:35,  1.17s/it]

Batches:  82%|████████▏ | 616/748 [12:20<02:34,  1.17s/it]

Batches:  82%|████████▏ | 617/748 [12:22<02:34,  1.18s/it]

Batches:  83%|████████▎ | 618/748 [12:23<02:33,  1.18s/it]

Batches:  83%|████████▎ | 619/748 [12:24<02:32,  1.18s/it]

Batches:  83%|████████▎ | 620/748 [12:25<02:31,  1.18s/it]

Batches:  83%|████████▎ | 621/748 [12:26<02:30,  1.18s/it]

Batches:  83%|████████▎ | 622/748 [12:28<02:29,  1.19s/it]

Batches:  83%|████████▎ | 623/748 [12:29<02:26,  1.17s/it]

Batches:  83%|████████▎ | 624/748 [12:30<02:33,  1.24s/it]

Batches:  84%|████████▎ | 625/748 [12:31<02:27,  1.20s/it]

Batches:  84%|████████▎ | 626/748 [12:32<02:25,  1.19s/it]

Batches:  84%|████████▍ | 627/748 [12:33<02:21,  1.17s/it]

Batches:  84%|████████▍ | 628/748 [12:35<02:20,  1.17s/it]

Batches:  84%|████████▍ | 629/748 [12:36<02:19,  1.17s/it]

Batches:  84%|████████▍ | 630/748 [12:37<02:16,  1.16s/it]

Batches:  84%|████████▍ | 631/748 [12:38<02:16,  1.17s/it]

Batches:  84%|████████▍ | 632/748 [12:39<02:11,  1.13s/it]

Batches:  85%|████████▍ | 633/748 [12:40<02:07,  1.11s/it]

Batches:  85%|████████▍ | 634/748 [12:41<02:09,  1.14s/it]

Batches:  85%|████████▍ | 635/748 [12:42<02:03,  1.09s/it]

Batches:  85%|████████▌ | 636/748 [12:44<02:05,  1.12s/it]

Batches:  85%|████████▌ | 637/748 [12:45<02:06,  1.14s/it]

Batches:  85%|████████▌ | 638/748 [12:46<02:06,  1.15s/it]

Batches:  85%|████████▌ | 639/748 [12:47<02:06,  1.16s/it]

Batches:  86%|████████▌ | 640/748 [12:48<02:06,  1.17s/it]

Batches:  86%|████████▌ | 641/748 [12:50<02:05,  1.17s/it]

Batches:  86%|████████▌ | 642/748 [12:51<02:03,  1.17s/it]

Batches:  86%|████████▌ | 643/748 [12:52<02:00,  1.14s/it]

Batches:  86%|████████▌ | 644/748 [12:53<02:00,  1.16s/it]

Batches:  86%|████████▌ | 645/748 [12:54<01:53,  1.10s/it]

Batches:  86%|████████▋ | 646/748 [12:55<01:51,  1.09s/it]

Batches:  86%|████████▋ | 647/748 [12:56<01:48,  1.08s/it]

Batches:  87%|████████▋ | 648/748 [12:57<01:44,  1.05s/it]

Batches:  87%|████████▋ | 649/748 [12:58<01:42,  1.03s/it]

Batches:  87%|████████▋ | 650/748 [12:59<01:43,  1.05s/it]

Batches:  87%|████████▋ | 651/748 [13:00<01:45,  1.09s/it]

Batches:  87%|████████▋ | 652/748 [13:02<01:47,  1.12s/it]

Batches:  87%|████████▋ | 653/748 [13:03<01:47,  1.14s/it]

Batches:  87%|████████▋ | 654/748 [13:04<01:47,  1.14s/it]

Batches:  88%|████████▊ | 655/748 [13:05<01:41,  1.09s/it]

Batches:  88%|████████▊ | 656/748 [13:06<01:34,  1.03s/it]

Batches:  88%|████████▊ | 657/748 [13:07<01:37,  1.07s/it]

Batches:  88%|████████▊ | 658/748 [13:08<01:37,  1.08s/it]

Batches:  88%|████████▊ | 659/748 [13:09<01:35,  1.07s/it]

Batches:  88%|████████▊ | 660/748 [13:10<01:34,  1.07s/it]

Batches:  88%|████████▊ | 661/748 [13:11<01:40,  1.15s/it]

Batches:  89%|████████▊ | 662/748 [13:12<01:31,  1.06s/it]

Batches:  89%|████████▊ | 663/748 [13:13<01:23,  1.02it/s]

Batches:  89%|████████▉ | 664/748 [13:14<01:19,  1.06it/s]

Batches:  89%|████████▉ | 665/748 [13:15<01:23,  1.01s/it]

Batches:  89%|████████▉ | 666/748 [13:16<01:27,  1.06s/it]

Batches:  89%|████████▉ | 667/748 [13:17<01:24,  1.04s/it]

Batches:  89%|████████▉ | 668/748 [13:18<01:18,  1.03it/s]

Batches:  89%|████████▉ | 669/748 [13:19<01:12,  1.09it/s]

Batches:  90%|████████▉ | 670/748 [13:20<01:15,  1.03it/s]

Batches:  90%|████████▉ | 671/748 [13:21<01:12,  1.06it/s]

Batches:  90%|████████▉ | 672/748 [13:22<01:09,  1.10it/s]

Batches:  90%|████████▉ | 673/748 [13:23<01:06,  1.13it/s]

Batches:  90%|█████████ | 674/748 [13:23<01:03,  1.16it/s]

Batches:  90%|█████████ | 675/748 [13:24<01:05,  1.11it/s]

Batches:  90%|█████████ | 676/748 [13:25<01:02,  1.16it/s]

Batches:  91%|█████████ | 677/748 [13:26<00:59,  1.20it/s]

Batches:  91%|█████████ | 678/748 [13:27<00:56,  1.23it/s]

Batches:  91%|█████████ | 679/748 [13:28<01:00,  1.15it/s]

Batches:  91%|█████████ | 680/748 [13:28<00:57,  1.19it/s]

Batches:  91%|█████████ | 681/748 [13:29<00:54,  1.23it/s]

Batches:  91%|█████████ | 682/748 [13:30<00:54,  1.21it/s]

Batches:  91%|█████████▏| 683/748 [13:31<00:52,  1.24it/s]

Batches:  91%|█████████▏| 684/748 [13:32<00:51,  1.25it/s]

Batches:  92%|█████████▏| 685/748 [13:32<00:51,  1.21it/s]

Batches:  92%|█████████▏| 686/748 [13:33<00:49,  1.25it/s]

Batches:  92%|█████████▏| 687/748 [13:34<00:48,  1.27it/s]

Batches:  92%|█████████▏| 688/748 [13:35<00:46,  1.30it/s]

Batches:  92%|█████████▏| 689/748 [13:35<00:43,  1.35it/s]

Batches:  92%|█████████▏| 690/748 [13:36<00:43,  1.35it/s]

Batches:  92%|█████████▏| 691/748 [13:37<00:44,  1.28it/s]

Batches:  93%|█████████▎| 692/748 [13:38<00:42,  1.33it/s]

Batches:  93%|█████████▎| 693/748 [13:38<00:40,  1.37it/s]

Batches:  93%|█████████▎| 694/748 [13:39<00:41,  1.31it/s]

Batches:  93%|█████████▎| 695/748 [13:40<00:38,  1.38it/s]

Batches:  93%|█████████▎| 696/748 [13:40<00:37,  1.40it/s]

Batches:  93%|█████████▎| 697/748 [13:41<00:35,  1.43it/s]

Batches:  93%|█████████▎| 698/748 [13:42<00:34,  1.45it/s]

Batches:  93%|█████████▎| 699/748 [13:42<00:33,  1.46it/s]

Batches:  94%|█████████▎| 700/748 [13:43<00:34,  1.39it/s]

Batches:  94%|█████████▎| 701/748 [13:44<00:32,  1.43it/s]

Batches:  94%|█████████▍| 702/748 [13:45<00:31,  1.48it/s]

Batches:  94%|█████████▍| 703/748 [13:45<00:30,  1.50it/s]

Batches:  94%|█████████▍| 704/748 [13:46<00:28,  1.53it/s]

Batches:  94%|█████████▍| 705/748 [13:46<00:27,  1.56it/s]

Batches:  94%|█████████▍| 706/748 [13:47<00:26,  1.58it/s]

Batches:  95%|█████████▍| 707/748 [13:48<00:25,  1.58it/s]

Batches:  95%|█████████▍| 708/748 [13:48<00:26,  1.51it/s]

Batches:  95%|█████████▍| 709/748 [13:49<00:24,  1.59it/s]

Batches:  95%|█████████▍| 710/748 [13:50<00:23,  1.61it/s]

Batches:  95%|█████████▌| 711/748 [13:50<00:22,  1.66it/s]

Batches:  95%|█████████▌| 712/748 [13:51<00:22,  1.58it/s]

Batches:  95%|█████████▌| 713/748 [13:51<00:21,  1.65it/s]

Batches:  95%|█████████▌| 714/748 [13:52<00:19,  1.71it/s]

Batches:  96%|█████████▌| 715/748 [13:53<00:19,  1.67it/s]

Batches:  96%|█████████▌| 716/748 [13:53<00:18,  1.74it/s]

Batches:  96%|█████████▌| 717/748 [13:54<00:17,  1.80it/s]

Batches:  96%|█████████▌| 718/748 [13:54<00:16,  1.84it/s]

Batches:  96%|█████████▌| 719/748 [13:55<00:15,  1.88it/s]

Batches:  96%|█████████▋| 720/748 [13:55<00:16,  1.68it/s]

Batches:  96%|█████████▋| 721/748 [13:56<00:15,  1.77it/s]

Batches:  97%|█████████▋| 722/748 [13:56<00:14,  1.81it/s]

Batches:  97%|█████████▋| 723/748 [13:57<00:13,  1.88it/s]

Batches:  97%|█████████▋| 724/748 [13:57<00:12,  1.91it/s]

Batches:  97%|█████████▋| 725/748 [13:58<00:11,  1.98it/s]

Batches:  97%|█████████▋| 726/748 [13:58<00:10,  2.00it/s]

Batches:  97%|█████████▋| 727/748 [13:59<00:10,  2.01it/s]

Batches:  97%|█████████▋| 728/748 [13:59<00:09,  2.02it/s]

Batches:  97%|█████████▋| 729/748 [14:00<00:09,  2.08it/s]

Batches:  98%|█████████▊| 730/748 [14:00<00:08,  2.15it/s]

Batches:  98%|█████████▊| 731/748 [14:01<00:08,  2.12it/s]

Batches:  98%|█████████▊| 732/748 [14:01<00:07,  2.06it/s]

Batches:  98%|█████████▊| 733/748 [14:02<00:07,  2.14it/s]

Batches:  98%|█████████▊| 734/748 [14:02<00:06,  2.20it/s]

Batches:  98%|█████████▊| 735/748 [14:02<00:05,  2.28it/s]

Batches:  98%|█████████▊| 736/748 [14:03<00:05,  2.34it/s]

Batches:  99%|█████████▊| 737/748 [14:03<00:04,  2.42it/s]

Batches:  99%|█████████▊| 738/748 [14:04<00:04,  2.40it/s]

Batches:  99%|█████████▉| 739/748 [14:04<00:03,  2.57it/s]

Batches:  99%|█████████▉| 740/748 [14:04<00:03,  2.66it/s]

Batches:  99%|█████████▉| 741/748 [14:05<00:02,  2.61it/s]

Batches:  99%|█████████▉| 742/748 [14:05<00:02,  2.69it/s]

Batches:  99%|█████████▉| 743/748 [14:05<00:01,  2.78it/s]

Batches:  99%|█████████▉| 744/748 [14:06<00:01,  2.88it/s]

Batches: 100%|█████████▉| 745/748 [14:06<00:00,  3.02it/s]

Batches: 100%|█████████▉| 746/748 [14:06<00:00,  2.93it/s]

Batches: 100%|█████████▉| 747/748 [14:07<00:00,  3.24it/s]

Batches: 100%|██████████| 748/748 [14:07<00:00,  2.99it/s]

Batches: 100%|██████████| 748/748 [14:07<00:00,  1.13s/it]

Batches:   0%|          | 0/40 [00:00<?, ?it/s]

Batches:   2%|▎         | 1/40 [00:00<00:07,  5.33it/s]

Batches:   5%|▌         | 2/40 [00:00<00:07,  5.03it/s]

Batches:   8%|▊         | 3/40 [00:00<00:05,  6.19it/s]

Batches:  10%|█         | 4/40 [00:00<00:05,  7.01it/s]

Batches:  12%|█▎        | 5/40 [00:00<00:06,  5.12it/s]

Batches:  15%|█▌        | 6/40 [00:01<00:05,  6.00it/s]

Batches:  18%|█▊        | 7/40 [00:01<00:04,  6.77it/s]

Batches:  20%|██        | 8/40 [00:01<00:04,  7.36it/s]

Batches:  22%|██▎       | 9/40 [00:01<00:03,  7.98it/s]

Batches:  25%|██▌       | 10/40 [00:01<00:03,  8.40it/s]

Batches:  28%|██▊       | 11/40 [00:01<00:03,  8.73it/s]

Batches:  32%|███▎      | 13/40 [00:01<00:02,  9.43it/s]

Batches:  35%|███▌      | 14/40 [00:01<00:02,  9.23it/s]

Batches:  40%|████      | 16/40 [00:02<00:02,  9.48it/s]

Batches:  45%|████▌     | 18/40 [00:02<00:02,  9.81it/s]

Batches:  48%|████▊     | 19/40 [00:02<00:02,  9.74it/s]

Batches:  52%|█████▎    | 21/40 [00:02<00:01, 10.02it/s]

Batches:  55%|█████▌    | 22/40 [00:02<00:01,  9.74it/s]

Batches:  60%|██████    | 24/40 [00:02<00:01, 10.29it/s]

Batches:  65%|██████▌   | 26/40 [00:03<00:01, 10.38it/s]

Batches:  70%|███████   | 28/40 [00:03<00:01, 10.85it/s]

Batches:  75%|███████▌  | 30/40 [00:03<00:00, 11.37it/s]

Batches:  80%|████████  | 32/40 [00:03<00:00, 11.48it/s]

Batches:  85%|████████▌ | 34/40 [00:03<00:00, 11.50it/s]

Batches:  90%|█████████ | 36/40 [00:03<00:00, 11.76it/s]

Batches:  95%|█████████▌| 38/40 [00:04<00:00, 12.22it/s]

Batches: 100%|██████████| 40/40 [00:04<00:00,  9.75it/s]

после обучения -> recall@50: 0.648  recall@200: 0.8651  (unseen 0.667  seen 0.616 )